version: '3.1'

services:
    mysql:
        image: mysql:latest
        ports:
            - '6000:3306'
        environment:
            MYSQL_ROOT_PASSWORD: Password#12345
        command: --bind-address=0.0.0.0
        networks:
            - sequelize-network
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - '8080:80'
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: Password#12345
        networks:
            - sequelize-network
        depends_on:
            - mysql
        restart: always

networks:
    sequelize-network:
